### ISSUE TITLE
Search: Title excluding pattern not working

### ISSUE THREAD

**Issue by Flyfish233** [yjl9903/AnimeGarden#1117]
### Describe the bug

Pattern:
`标题:"Girls Band Cry" 标题:排除:繁體`

- Filter "标题:排除:繁體" not working.

> `排除:xxx 或者 -xxx`：返回的每一条结果的标题不能包含其指定的所有关键词.

Expected behavior: It should return titles that do not include `"繁體"`,  but it returned the same results as the pattern `标题:"Girls Band Cry"`, which includes:

- [北宇治字幕组] GIRLS BAND CRY [02][WebRip][HEVC_AAC][繁體內嵌]
- [桜都字幕組] Girls Band Cry / Girls Band Cry [01][1080p][繁體內嵌]
...

### Browser Info

```Shell
Any
```

**Comment by yjl9903** [comment]
Not `标题：排除：xxx`，just `排除：`

You can preview the actual filter conditions applied on the search result page.

**Comment by yjl9903** [comment]
By the way to avoid miss understanding, I will accept this pattern.

**Comment by Flyfish233** [comment]
When typing `标题:"Girls Band Cry" 排除:繁體` on search bar, it will automatically change to `标题:"Girls Band Cry" 标题:排除:繁體`. Maybe that's why causing this issue?

**Comment by yjl9903** [comment]
> When searching `标题:"Girls Band Cry" 排除:繁體` on search bar, it will automatically change to `标题:"Girls Band Cry" 标题:排除:繁體`. Maybe that's why causing this issue?

I will check it tonight.

**Comment by yjl9903** [comment]
@Flyfish233 Fixed
