### ISSUE TITLE
从首页的日程表点进去“【我推的孩子】 第2季”所生成的RSS订阅链接有问题

### ISSUE THREAD

**Issue by PLFJY** [yjl9903/AnimeGarden#1362]
### Describe the bug

从首页的日程表点进去“【我推的孩子】 第2季”后搜索出来的条目没有问题
但是点击RSS后所生成的RSS订阅链接返回{"status":400}
应该是RSS订阅链接有所问题

### Reproduction

https://garden.onekuma.cn/resources/1?after=1719360000000&include=%5B%22%E3%80%90%E6%8E%A8%E3%81%97%E3%81%AE%E5%AD%90%E3%80%91+%E7%AC%AC2%E6%9C%9F%22%2C%22%26quot%3BOshi+no+Ko%26quot%3B+2%22%2C%22%E3%80%90%E6%8E%A8%E3%81%97%E3%81%AE%E5%AD%90%E3%80%91%22%2C%22%E6%88%91%E6%8E%A8%E7%9A%84%E5%AD%A9%E5%AD%90%22%5D

### Browser Info

```Shell
Microsoft Edge
版本 125.0.2535.92 (正式版本) (64 位)
```

**Comment by yjl9903** [comment]
![image](https://github.com/yjl9903/AnimeGarden/assets/30072175/dc77dbbc-9361-46b9-91cf-1b247d654d90)

有一些奇怪的符号，晚上修复

**Comment by yjl9903** [comment]
Resolve in https://github.com/yjl9903/bgmc/pull/762 and https://github.com/yjl9903/AnimeGarden/commit/9afa3ccfa4d6f2e0cb04dafe783f991eb8eb256c
