### ISSUE TITLE
收藏夹功能里将多个搜索条件聚合成一个RSS订阅链接有误

### ISSUE THREAD

**Issue by coni233** [yjl9903/AnimeGarden#1389]
### Describe the bug

[收藏夹功能里将多个搜索条件聚合成一个RSS订阅链接后，生成的订阅链接无法使用，解析出来是{"status":400}，[我的整合连接](https://garden.onekuma.cn/feed.xml?filter=%5B%7B%22fansubId%22:%5B%22657%22%5D,%22include%22:%5B%22%E9%B9%BF%E4%B9%83%E5%AD%90%E4%B9%83%E5%AD%90%E4%B9%83%E5%AD%90%E8%99%8E%E8%A7%86%E7%9C%88%E7%9C%88%22%5D,%22keywords%22:%5B%22%E9%B9%BF%22%5D%7D,%7B%22fansubId%22:%5B%22657%22%5D,%22search%22:%5B%22%E5%B0%8F%E5%B8%82%E6%B0%91%E7%B3%BB%E5%88%97%22%5D%7D,%7B%22fansubId%22:%5B%22657%22%5D,%22include%22:%5B%22%E7%89%A9%E8%AF%AD%E7%B3%BB%E5%88%97%22,%22%E5%A4%96%E4%BC%A0%E5%AD%A3&%E6%80%AA%E7%89%A9%E5%AD%A3%22%5D%7D,%7B%22fansubId%22:%5B%22657%22%5D,%22keywords%22:%5B%22%5BLoliHouse%5D%22,%22%E3%80%90%E6%88%91%E6%8E%A8%E7%9A%84%E5%AD%A9%E5%AD%90%E3%80%91%22%5D%7D%5D)
这个功能我还挺喜欢的，蜜柑计划那个订阅整合也经常有bug

### Browser Info

```Shell
{"status":400}
```

**Comment by yjl9903** [comment]
感谢支持。

URL 里有一个意外的 "&" 符号 （物语 外传季&怪物季），可以先去掉。

**Comment by yjl9903** [comment]
Fixed in https://github.com/yjl9903/AnimeGarden/commit/a8b00591b5cf86557622e45e0281733fa8cb3aec
