### ISSUE TITLE
链接尾部总有undefined

### ISSUE THREAD

**Issue by red-co** [yjl9903/AnimeGarden#1469]
### Describe the bug

从 昨天?今天 开始，例子: magnet:?xt=urn:btih:L2S6L5NZ2DRVAHWQPISAQ3URETIYOXQSundefined

**Comment by yjl9903** [comment]
可以麻烦提供一下是什么页面出现了这种链接吗？

**Comment by yjl9903** [comment]
Fixed in https://github.com/yjl9903/AnimeGarden/commit/6c7fdb3f2f2fd29fab9748bc9bd3b32f972fe46b
