### ISSUE TITLE
无法进行搜索

### ISSUE THREAD

**Issue by Otakusama114** [yjl9903/AnimeGarden#1528]
### 描述

输入字符后，无法在搜索框进行搜索

### 浏览器信息

```Shell
com.android.browser
14.6.72
```

**Comment by yjl9903** [comment]
无法搜索具体指的是什么？

期望是：输入字符，按回车，页面顶部出现 loading 条，等一会跳转到搜索结果页面（可能有点慢）。

**Comment by yjl9903** [comment]
搜索接口近期并发请求量非常大，出现超时错误，待排查原因。
