### ISSUE TITLE
[BUG] 搜索功能无法工作，HTTP 524

### ISSUE THREAD

**Issue by crrashh1542** [yjl9903/AnimeGarden#1573]
### 描述

当搜索任意内容时，均会出现CloudFlare的报错界面，错误信息为：`524 | A time out occurred`

![Screenshot_2024-12-06-01-10-55-095_mark via-edit](https://github.com/user-attachments/assets/e1f85edf-fffb-4728-8a44-32bb87211dd8)

### 复现链接

https://garden.breadio.wiki/resources/1?search= `{ anyTextHere: string }`

### 浏览器信息

```Shell
mark.via                     6.0.0 (20241106)
com.google.android.webview   129.0.6668.100 (666810033)
```

**Comment by yjl9903** [comment]
现在呢，前两天服务器供应商出了事故

**Comment by crrashh1542** [comment]
> 现在呢，前两天服务器供应商出了事故

若点击首页`weekly-content`提供的预设搜索内容则可正常访问搜索功能
![image](https://github.com/user-attachments/assets/ecac0d14-b2e3-4822-9a57-4ae4da65c583)
若手动输入番剧标题内容，则无法工作，出现HTTP 524的情况
![image](https://github.com/user-attachments/assets/d71a4ac9-0902-4088-9c4e-f6c333455716)

**Comment by yjl9903** [comment]
@crrashh1542 重启了部分中间件和服务, 现在呢?

By the way 寒假前不鸽的话, 有搜索功能的整体优化

**Comment by yjl9903** [comment]
tg group: https://t.me/+QLdRRqoDt1gxMWZl

**Comment by crrashh1542** [comment]
> @crrashh1542 重启了部分中间件和服务, 现在呢?
> 
> By the way 寒假前不鸽的话, 有搜索功能的整体优化

功能已恢复正常，thx👌
