### ISSUE TITLE
bug: 搜索框无法输入 s 和 /

### ISSUE THREAD

**Issue by Teiiiiiio** [yjl9903/AnimeGarden#386]
### Clear and concise description of the problem

[Search.tsx](https://github.com/yjl9903/AnimeGarden/blob/10250231de960a28bd48a3e8170e064586973851/packages/app/src/components/Search.tsx#L17)
```
  document.addEventListener('keypress', (ev) => {
    if (ev.key === 's' || ev.key === '/') {
      const input = document.querySelector('#animegarden-search input');
      // @ts-ignore
      input?.focus();
      ev.preventDefault();
      ev.stopPropagation();
    }
  });
```
输入s或者/会focus到input上用于快速输入,我认为主页的搜索框无法输入s的行为很怪异
不确认这是否是有意的行为,所以我没有提交为bug issue

### Suggested solution

可以保留/

**Comment by yjl9903** [comment]
`/` 和我的插件 (Vimium C) 冲突了

**Comment by Teiiiiiio** [comment]
> 判一下是否已经 focus 到搜索框，未 focus 就 focus，否则正常输入
感觉这个更适合

fork之后发现已经更新成这个逻辑了XD
