### ISSUE TITLE
how to dev locally

### ISSUE THREAD

**Issue by Teiiiiiio** [yjl9903/AnimeGarden#394]
当我在本地执行了`pnpm run dev`后,`web app`打开会报错`TypeError: Cannot read properties of undefined (reading 'env')`
然后我搜索了`Astro.locals.runtime.env`,得知这是Cloudflare的runtime,所以dev时也需要部署到Cf上吗

**Comment by yjl9903** [comment]
更新了 astro 3.0 之后，获取这个东西的方式修改了，现在只是调整了能正常 build，本地开发还没看

**Comment by yjl9903** [comment]
https://github.com/yjl9903/AnimeGarden/blob/17c8c4c1b4187a90c17547389c505439528ad13e/packages/app/src/utils.ts#L7-L10

```ts
 export function getRuntimeEnv(locals: App.Locals): Env | undefined { 
   // @ts-ignore 
   return locals?.runtime?.env; 
 } 
```

**Comment by yjl9903** [comment]
Fixed in https://github.com/yjl9903/AnimeGarden/commit/b2b8f6fd377c2173d345df652f7e78e0bf1143b1

**Comment by Teiiiiiio** [comment]
@yjl9903  感谢,我去试试能不能本地开发,或者build一个放到cf上
顺便问一下有没有详细点的部署教程呢,没有接触过cf

**Comment by yjl9903** [comment]
> @yjl9903 感谢,我去试试能不能本地开发,或者build一个放到cf上 顺便问一下有没有详细点的部署教程呢,没有接触过cf

可能晚点补充一些如何自己部署的教程。

**Comment by Teiiiiiio** [comment]
@yjl9903 
* 修复dev的Type报错后,遇到了fetch的错误,`https://animegarden.yjl9903.workers.dev/`是可以访问到的,不知道为什么会出现错误🤔
![image](https://github.com/yjl9903/AnimeGarden/assets/87224935/063bd859-cc34-430d-9bad-73786e6db60b)
![image](https://github.com/yjl9903/AnimeGarden/assets/87224935/b87ab4e6-86eb-4a3a-9f32-87186ecb2cd2)

* 把`packages/app/src/fetch.ts`中的`baseURL`改成调用你的API后在本地成功运行了
  ![image](https://github.com/yjl9903/AnimeGarden/assets/87224935/d3dca506-1b62-4506-a6a5-8ae6d0a95b8d)
  ```
  原
  export const WORKER_BASE = `animegarden.yjl9903.workers.dev`;
  const baseURL = 'https://' + (import.meta.env.SSR ? WORKER_BASE : 'garden.onekuma.cn/api/');
  
  新
  const baseURL = 'https://' + (import.meta.env.SSR ? 'garden.onekuma.cn/api/' : 'garden.onekuma.cn/api/');
  ```

* 运行一秒后会在`packages\app\src\layouts\Layout.astro`的`timestamp`变量出现type错误,给env添加可选链符后正常运行
   ![image](https://github.com/yjl9903/AnimeGarden/assets/87224935/876349d2-c2d4-4e58-82d9-c25d00fb5fca)
   ```
  原
  const timestamp = Astro.props.timestamp ?? new Date((await env.animegarden.get('state/refresh-timestamp')) ?? 0);

  新
  const timestamp = Astro.props.timestamp ?? new Date((await env?.animegarden.get('state/refresh-timestamp')) ?? 0);
  ```
至此已经解决了本地开发的问题,虽然用的都是你的worker XD

然后折腾了下部署,请教下两个问题
1. 新注册的PlanetScale,好像得绑定信用卡和借记卡才允许创建数据库了,有没有别的方法
    ![image](https://github.com/yjl9903/AnimeGarden/assets/87224935/8d476de3-53ed-4ef9-972d-b1dbace2c152)
2. 根据下面发的配置图来看,web pages是build后把dist文件夹direct upload吗,原理是什么呢?没看到有页面的入口文件
    ![image](https://github.com/yjl9903/AnimeGarden/assets/87224935/257715ca-1a38-4451-8f79-75dbbfa99c4e)
    ![image](https://github.com/yjl9903/AnimeGarden/assets/87224935/c18a2036-6fac-43ed-9aa3-6957d2261e42)

**Comment by yjl9903** [comment]
1. PlanetScale 看了一下我这里是没有绑信用卡的 (4 月注册的), 不清楚是否有什么变动, 或许可以直接发 email 联系它让你白嫖 (之前 netlify 用超额度, 发 email 白嫖了一下)
2. Pages 连接你的 repo 即可

**Comment by yjl9903** [comment]
timestamp fixed in https://github.com/yjl9903/AnimeGarden/commit/b63645aaf01319845db04f1e15564c3d22408a05

**Comment by yjl9903** [comment]
P.S. 自己部署的话 kv namespace 免费额度的 write 应该顶不住

**Comment by yjl9903** [comment]
worker 的链接配置我晚点在看一下 (

可能可以加一下让它走本地起的 worker

**Comment by Teiiiiiio** [comment]
那我先白嫖你的worker在本地做一些前端的PR
btw,分页好像失效了,`garden.onekuma.cn`上下页都只能获取第一页的数据
`https://garden.onekuma.cn/api/resources?page=2`能正常获取第二页的数据

**Comment by yjl9903** [comment]
> 那我先白嫖你的worker在本地做一些前端的PR btw,分页好像失效了,`garden.onekuma.cn`上下页都只能获取第一页的数据 `https://garden.onekuma.cn/api/resources?page=2`能正常获取第二页的数据

Pagination fixed
