### ISSUE TITLE
feat(app): clear history search

### ISSUE THREAD

**Issue by Teiiiiiio** [yjl9903/AnimeGarden#401]
### Clear and concise description of the problem

- add `"清空" button` to clear all search history
- add `close icon button` to clear click item history

**Comment by Teiiiiiio** [comment]
WIP

**Comment by yjl9903** [comment]
![image](https://github.com/yjl9903/AnimeGarden/assets/30072175/0b8a2589-3044-4078-aca5-bb5c8db9a769)

完善了一些样式:

+ 居中和加大了图标
+ 对齐了清空

添加了一些 `ev.stopPropagation()`
